export const EPISODE_LIST_REQUEST = 'EPISODE_LIST_REQUEST';
export const EPISODE_LIST_SUCCESS = 'EPISODE_LIST_SUCCESS';
export const EPISODE_LIST_FAIL = 'EPISODE_LIST_FAIL';

export const EPISODE_DETAILS_REQUEST = 'EPISODE_DETAILS_REQUEST';
export const EPISODE_DETAILS_SUCCESS = 'EPISODE_DETAILS_SUCCESS';
export const EPISODE_DETAILS_FAIL = 'EPISODE_DETAILS_FAIL';
export const EPISODE_DETAILS_RESET = 'EPISODE_DETAILS_RESET';
