export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST';
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL';

export const LOCATION_DETAILS_REQUEST = ' LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = ' LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAIL = ' LOCATION_DETAILS_FAIL';
export const LOCATION_DETAILS_RESET = ' LOCATION_DETAILS_RESET';
