export const CHECK_BOX_WATCH_LIST = 'CHECK_BOX_WATCH_LIST';

export const REMOVE_EPISODE_FROM_WATCH_LIST = 'REMOVE_EPISODE_FROM_WATCH_LIST';

export const CLEAR_WATCH_LIST = 'CLEAR_WATCH_LIST';


export const ADD_TO_WATCH_LIST_REQUEST = 'ADD_TO_WATCH_LIST_REQUEST';
export const ADD_TO_WATCH_LIST_SUCCESS = 'ADD_TO_WATCH_LIST_SUCCESS';
export const ADD_TO_WATCH_LIST_FAIL = 'ADD_TO_WATCH_LIST_FAIL';
